/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.vendingMachine;

import javax.swing.JOptionPane;

/**
 *
 * @author brady
 */
public class FloatFrame extends javax.swing.JFrame {

    /**
     * Creates new form FloatFrame
     */
    public FloatFrame() {
        initComponents();
        // Set initial values for coin count displays
        jTextField2EuroTotal.setText("" + VendingMachine.coinCounts[0]);
        jTextField1EuroTotal.setText("" + VendingMachine.coinCounts[1]);
        jTextField50CentTotal.setText("" + VendingMachine.coinCounts[2]);
        jTextField20CentTotal.setText("" + VendingMachine.coinCounts[3]);
        jTextField10CentTotal.setText("" + VendingMachine.coinCounts[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton20CentAdd = new javax.swing.JButton();
        jLabel2Euro = new javax.swing.JLabel();
        jButton50CentMinus = new javax.swing.JButton();
        jLabel1Euro = new javax.swing.JLabel();
        jTextField2EuroTotal = new javax.swing.JTextField();
        jLabel20Cent = new javax.swing.JLabel();
        jTextField1EuroTotal = new javax.swing.JTextField();
        jLabel50Cent = new javax.swing.JLabel();
        jTextField50CentTotal = new javax.swing.JTextField();
        jButton2EuroAdd = new javax.swing.JButton();
        jTextField20CentTotal = new javax.swing.JTextField();
        jButton20CentMinus = new javax.swing.JButton();
        jToggleButtonExit = new javax.swing.JToggleButton();
        jButton1EuroAdd = new javax.swing.JButton();
        jLabelFloat = new javax.swing.JLabel();
        jButton2EuroMinus = new javax.swing.JButton();
        jButton50CentAdd = new javax.swing.JButton();
        jButton1EuroMinus = new javax.swing.JButton();
        jLabel10Cent = new javax.swing.JLabel();
        jButton10CentAdd = new javax.swing.JButton();
        jButton10CentMinus = new javax.swing.JButton();
        jTextField10CentTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Float");

        jButton20CentAdd.setText("+");
        jButton20CentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20CentAddActionPerformed(evt);
            }
        });

        jLabel2Euro.setText("2€");

        jButton50CentMinus.setText("-");
        jButton50CentMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50CentMinusActionPerformed(evt);
            }
        });

        jLabel1Euro.setText("1€");

        jTextField2EuroTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2EuroTotalActionPerformed(evt);
            }
        });

        jLabel20Cent.setText("20c");

        jTextField1EuroTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1EuroTotalActionPerformed(evt);
            }
        });

        jLabel50Cent.setText("50c");

        jTextField50CentTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField50CentTotalActionPerformed(evt);
            }
        });

        jButton2EuroAdd.setText("+");
        jButton2EuroAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EuroAddActionPerformed(evt);
            }
        });

        jTextField20CentTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20CentTotalActionPerformed(evt);
            }
        });

        jButton20CentMinus.setText("-");
        jButton20CentMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20CentMinusActionPerformed(evt);
            }
        });

        jToggleButtonExit.setText("EXIT");
        jToggleButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonExitActionPerformed(evt);
            }
        });

        jButton1EuroAdd.setText("+");
        jButton1EuroAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EuroAddActionPerformed(evt);
            }
        });

        jLabelFloat.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelFloat.setText("FLOAT");

        jButton2EuroMinus.setText("-");
        jButton2EuroMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EuroMinusActionPerformed(evt);
            }
        });

        jButton50CentAdd.setText("+");
        jButton50CentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50CentAddActionPerformed(evt);
            }
        });

        jButton1EuroMinus.setText("-");
        jButton1EuroMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EuroMinusActionPerformed(evt);
            }
        });

        jLabel10Cent.setText("10c");

        jButton10CentAdd.setText("+");
        jButton10CentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10CentAddActionPerformed(evt);
            }
        });

        jButton10CentMinus.setText("-");
        jButton10CentMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10CentMinusActionPerformed(evt);
            }
        });

        jTextField10CentTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10CentTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFloat)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2Euro)
                                            .addComponent(jLabel1Euro))
                                        .addGap(32, 32, 32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20Cent)
                                            .addComponent(jLabel50Cent)
                                            .addComponent(jLabel10Cent))
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton50CentAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(jButton10CentAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton20CentAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1EuroAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2EuroAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2EuroMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                    .addComponent(jButton1EuroMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton10CentMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton20CentMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton50CentMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2EuroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1EuroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField50CentTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField20CentTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10CentTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToggleButtonExit)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFloat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2EuroAdd)
                    .addComponent(jButton2EuroMinus)
                    .addComponent(jTextField2EuroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2Euro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1EuroAdd)
                    .addComponent(jLabel1Euro)
                    .addComponent(jTextField1EuroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1EuroMinus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton50CentAdd)
                    .addComponent(jTextField50CentTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton50CentMinus)
                    .addComponent(jLabel50Cent))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20Cent)
                    .addComponent(jButton20CentAdd)
                    .addComponent(jButton20CentMinus)
                    .addComponent(jTextField20CentTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10CentTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10CentAdd)
                    .addComponent(jButton10CentMinus)
                    .addComponent(jLabel10Cent))
                .addGap(17, 17, 17)
                .addComponent(jToggleButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton50CentMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50CentMinusActionPerformed
        if (VendingMachine.coinCounts[2] > 0) { // If coint count is greater than 0 it decrements it by one
            VendingMachine.coinCounts[2]--; 
            jTextField50CentTotal.setText("" + VendingMachine.coinCounts[2]);
        } else {   
             JOptionPane.showMessageDialog(null, "50 Cent coin cannot be negative!"); // Otherwise stock cannot be negative
        }
    }//GEN-LAST:event_jButton50CentMinusActionPerformed

    private void jButton10CentMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10CentMinusActionPerformed
        if (VendingMachine.coinCounts[4] > 0) {
            VendingMachine.coinCounts[4]--;
            jTextField10CentTotal.setText("" + VendingMachine.coinCounts[4]);
        } else {
            JOptionPane.showMessageDialog(null, "10 Cent coin cannot be negative!");
        }
    }//GEN-LAST:event_jButton10CentMinusActionPerformed

    private void jButton20CentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20CentAddActionPerformed
       VendingMachine.coinCounts[3]++; // Increment coin
       jTextField20CentTotal.setText("" + VendingMachine.coinCounts[3]);
    }//GEN-LAST:event_jButton20CentAddActionPerformed

    private void jToggleButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonExitActionPerformed
      VendingMachine v = new VendingMachine();
        v.setVisible(true);
        dispose(); // Close the frame and open Vending Machine Frame
    }//GEN-LAST:event_jToggleButtonExitActionPerformed

    private void jTextField2EuroTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2EuroTotalActionPerformed
       VendingMachine.coinCounts[0]++;
       jTextField2EuroTotal.setText("" + VendingMachine.coinCounts[0]);
    }//GEN-LAST:event_jTextField2EuroTotalActionPerformed

    private void jTextField1EuroTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1EuroTotalActionPerformed
       VendingMachine.coinCounts[1]++;
       jTextField1EuroTotal.setText("" + VendingMachine.coinCounts[1]);
    }//GEN-LAST:event_jTextField1EuroTotalActionPerformed

    private void jTextField50CentTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField50CentTotalActionPerformed
       VendingMachine.coinCounts[2]++;
    }//GEN-LAST:event_jTextField50CentTotalActionPerformed

    private void jTextField20CentTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20CentTotalActionPerformed
       VendingMachine.coinCounts[4]++;
    }//GEN-LAST:event_jTextField20CentTotalActionPerformed

    private void jTextField10CentTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10CentTotalActionPerformed
       VendingMachine.coinCounts[2]++;
    }//GEN-LAST:event_jTextField10CentTotalActionPerformed

    private void jButton2EuroMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EuroMinusActionPerformed
       if (VendingMachine.coinCounts[0] > 0) {
            VendingMachine.coinCounts[0]--;
            jTextField2EuroTotal.setText("" + VendingMachine.coinCounts[0]);
        } else {   
             JOptionPane.showMessageDialog(null, "2 Euro coin cannot be negative!");
       }
    }//GEN-LAST:event_jButton2EuroMinusActionPerformed

    private void jButton1EuroMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EuroMinusActionPerformed
        if (VendingMachine.coinCounts[1] > 0) {
            VendingMachine.coinCounts[1]--;
            jTextField1EuroTotal.setText("" + VendingMachine.coinCounts[1]);
        } else {   
             JOptionPane.showMessageDialog(null, "1 Euro coin cannot be negative!"); 
        }
    }//GEN-LAST:event_jButton1EuroMinusActionPerformed

    private void jButton20CentMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20CentMinusActionPerformed
        if (VendingMachine.coinCounts[3] > 0) {
            VendingMachine.coinCounts[3]--;
            jTextField20CentTotal.setText("" + VendingMachine.coinCounts[3]);
        } else {   
             JOptionPane.showMessageDialog(null, "20 Cent coin cannot be negative!");
        }
    }//GEN-LAST:event_jButton20CentMinusActionPerformed

    private void jButton1EuroAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EuroAddActionPerformed
            VendingMachine.coinCounts[1]++;
            jTextField1EuroTotal.setText("" + VendingMachine.coinCounts[1]);
    }//GEN-LAST:event_jButton1EuroAddActionPerformed

    private void jButton50CentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50CentAddActionPerformed
            VendingMachine.coinCounts[2]++;
            jTextField50CentTotal.setText("" + VendingMachine.coinCounts[2]);
    }//GEN-LAST:event_jButton50CentAddActionPerformed

    private void jButton10CentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10CentAddActionPerformed
            VendingMachine.coinCounts[4]++;
            jTextField10CentTotal.setText("" + VendingMachine.coinCounts[4]);
    }//GEN-LAST:event_jButton10CentAddActionPerformed

    private void jButton2EuroAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EuroAddActionPerformed
           VendingMachine.coinCounts[0]++;
           jTextField2EuroTotal.setText("" + VendingMachine.coinCounts[0]);
    }//GEN-LAST:event_jButton2EuroAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FloatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FloatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FloatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FloatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FloatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10CentAdd;
    private javax.swing.JButton jButton10CentMinus;
    private javax.swing.JButton jButton1EuroAdd;
    private javax.swing.JButton jButton1EuroMinus;
    private javax.swing.JButton jButton20CentAdd;
    private javax.swing.JButton jButton20CentMinus;
    private javax.swing.JButton jButton2EuroAdd;
    private javax.swing.JButton jButton2EuroMinus;
    private javax.swing.JButton jButton50CentAdd;
    private javax.swing.JButton jButton50CentMinus;
    private javax.swing.JLabel jLabel10Cent;
    private javax.swing.JLabel jLabel1Euro;
    private javax.swing.JLabel jLabel20Cent;
    private javax.swing.JLabel jLabel2Euro;
    private javax.swing.JLabel jLabel50Cent;
    private javax.swing.JLabel jLabelFloat;
    private javax.swing.JTextField jTextField10CentTotal;
    private javax.swing.JTextField jTextField1EuroTotal;
    private javax.swing.JTextField jTextField20CentTotal;
    private javax.swing.JTextField jTextField2EuroTotal;
    private javax.swing.JTextField jTextField50CentTotal;
    private javax.swing.JToggleButton jToggleButtonExit;
    // End of variables declaration//GEN-END:variables
}
