/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.vendingMachine;

import javax.swing.JOptionPane;

/**
 *
 * @author brady
 */
public class StockFrame extends javax.swing.JFrame {

    /**
     * Creates new form StockFrame
     */
    public StockFrame() {
        initComponents();
        // Set initial values for stock count displays
        jTextFieldFantaTotal.setText("" + VendingMachine.drinkStock[0]);
        jTextFieldMonsterTotal.setText("" + VendingMachine.drinkStock[1]);
        jTextFieldLucozadeTotal.setText("" + VendingMachine.drinkStock[2]);
        jTextFieldPepsiTotal.setText("" + VendingMachine.drinkStock[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPepsi = new javax.swing.JLabel();
        jLabelMonster = new javax.swing.JLabel();
        jLabelFanta = new javax.swing.JLabel();
        jLabelLucozade = new javax.swing.JLabel();
        jButtonFantaAdd = new javax.swing.JButton();
        jButtonFantaMinus = new javax.swing.JButton();
        jButtonMonsterAdd = new javax.swing.JButton();
        jButtonMonsterMinus = new javax.swing.JButton();
        jButtonLucozadeAdd = new javax.swing.JButton();
        jButtonLucozadeMinus = new javax.swing.JButton();
        jButtonPepsiAdd = new javax.swing.JButton();
        jButtonPepsiMinus = new javax.swing.JButton();
        jTextFieldFantaTotal = new javax.swing.JTextField();
        jTextFieldLucozadeTotal = new javax.swing.JTextField();
        jTextFieldMonsterTotal = new javax.swing.JTextField();
        jTextFieldPepsiTotal = new javax.swing.JTextField();
        jLabelStock = new javax.swing.JLabel();
        jToggleButtonExit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock");

        jLabelPepsi.setText("Pepsi");

        jLabelMonster.setText("Monster");

        jLabelFanta.setText("Fanta");

        jLabelLucozade.setText("Lucozade");

        jButtonFantaAdd.setText("+");
        jButtonFantaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFantaAddActionPerformed(evt);
            }
        });

        jButtonFantaMinus.setText("-");
        jButtonFantaMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFantaMinusActionPerformed(evt);
            }
        });

        jButtonMonsterAdd.setText("+");
        jButtonMonsterAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMonsterAddActionPerformed(evt);
            }
        });

        jButtonMonsterMinus.setText("-");
        jButtonMonsterMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMonsterMinusActionPerformed(evt);
            }
        });

        jButtonLucozadeAdd.setText("+");
        jButtonLucozadeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLucozadeAddActionPerformed(evt);
            }
        });

        jButtonLucozadeMinus.setText("-");
        jButtonLucozadeMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLucozadeMinusActionPerformed(evt);
            }
        });

        jButtonPepsiAdd.setText("+");
        jButtonPepsiAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPepsiAddActionPerformed(evt);
            }
        });

        jButtonPepsiMinus.setText("-");
        jButtonPepsiMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPepsiMinusActionPerformed(evt);
            }
        });

        jTextFieldFantaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFantaTotalActionPerformed(evt);
            }
        });

        jLabelStock.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelStock.setText("STOCK");

        jToggleButtonExit.setText("EXIT");
        jToggleButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldMonsterTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelLucozade)
                                            .addComponent(jLabelMonster)
                                            .addComponent(jLabelPepsi))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonFantaAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                            .addComponent(jButtonMonsterAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonLucozadeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPepsiAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(41, 41, 41))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelStock)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonPepsiMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonLucozadeMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonMonsterMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFanta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonFantaMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jTextFieldFantaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldLucozadeTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPepsiTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonExit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFantaAdd)
                    .addComponent(jButtonFantaMinus)
                    .addComponent(jTextFieldFantaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFanta))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMonsterAdd)
                    .addComponent(jButtonMonsterMinus)
                    .addComponent(jLabelMonster)
                    .addComponent(jTextFieldMonsterTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLucozadeMinus)
                    .addComponent(jButtonLucozadeAdd)
                    .addComponent(jLabelLucozade)
                    .addComponent(jTextFieldLucozadeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPepsiMinus)
                    .addComponent(jButtonPepsiAdd)
                    .addComponent(jTextFieldPepsiTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPepsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPepsiMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPepsiMinusActionPerformed
        if (VendingMachine.drinkStock[3] > 0) {
            VendingMachine.drinkStock[3]--;
            jTextFieldPepsiTotal.setText("" + VendingMachine.drinkStock[3]);
        } else {
            JOptionPane.showMessageDialog(null, "Pepsi stock cannot be negative!");
        }
    }//GEN-LAST:event_jButtonPepsiMinusActionPerformed

    private void jButtonFantaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFantaAddActionPerformed
        VendingMachine.drinkStock[0]++;
        jTextFieldFantaTotal.setText("" + VendingMachine.drinkStock[0]);
    }//GEN-LAST:event_jButtonFantaAddActionPerformed

    private void jButtonFantaMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFantaMinusActionPerformed
        if (VendingMachine.drinkStock[0] > 0) {
            VendingMachine.drinkStock[0]--;
            jTextFieldFantaTotal.setText("" + VendingMachine.drinkStock[0]);
        } else {
            JOptionPane.showMessageDialog(null, "Fanta stock cannot be negative!");
        }
    }//GEN-LAST:event_jButtonFantaMinusActionPerformed

    private void jButtonMonsterAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMonsterAddActionPerformed
        VendingMachine.drinkStock[1]++;
        jTextFieldMonsterTotal.setText("" + VendingMachine.drinkStock[1]);
    }//GEN-LAST:event_jButtonMonsterAddActionPerformed

    private void jButtonMonsterMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMonsterMinusActionPerformed
        if (VendingMachine.drinkStock[1] > 0) {
            VendingMachine.drinkStock[1]--;
            jTextFieldMonsterTotal.setText("" + VendingMachine.drinkStock[1]);
        } else {
            JOptionPane.showMessageDialog(null, "Monster stock cannot be negative!");
        }    }//GEN-LAST:event_jButtonMonsterMinusActionPerformed

    private void jButtonLucozadeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLucozadeAddActionPerformed
        VendingMachine.drinkStock[2]++; // Add the drink
        jTextFieldLucozadeTotal.setText("" + VendingMachine.drinkStock[2]);
    }//GEN-LAST:event_jButtonLucozadeAddActionPerformed

    private void jButtonLucozadeMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLucozadeMinusActionPerformed
        if (VendingMachine.drinkStock[2] > 0) { // If drink stock is greater than zero, it will decrement the stock when clicked on minus button
            VendingMachine.drinkStock[2]--;
            jTextFieldLucozadeTotal.setText("" + VendingMachine.drinkStock[2]); 
        } else {
            JOptionPane.showMessageDialog(null, "Lucozade stock cannot be negative!"); // Otherwise will tell stock cannot be negative
        }
    }//GEN-LAST:event_jButtonLucozadeMinusActionPerformed

    private void jButtonPepsiAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPepsiAddActionPerformed
        VendingMachine.drinkStock[3]++;
        jTextFieldPepsiTotal.setText("" + VendingMachine.drinkStock[3]);
    }//GEN-LAST:event_jButtonPepsiAddActionPerformed

    private void jTextFieldFantaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFantaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFantaTotalActionPerformed

    private void jToggleButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonExitActionPerformed
        VendingMachine v = new VendingMachine();
        v.setVisible(true);
        dispose(); // Close the frame and open Vending Machine frame
    }//GEN-LAST:event_jToggleButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFantaAdd;
    private javax.swing.JButton jButtonFantaMinus;
    private javax.swing.JButton jButtonLucozadeAdd;
    private javax.swing.JButton jButtonLucozadeMinus;
    private javax.swing.JButton jButtonMonsterAdd;
    private javax.swing.JButton jButtonMonsterMinus;
    private javax.swing.JButton jButtonPepsiAdd;
    private javax.swing.JButton jButtonPepsiMinus;
    private javax.swing.JLabel jLabelFanta;
    private javax.swing.JLabel jLabelLucozade;
    private javax.swing.JLabel jLabelMonster;
    private javax.swing.JLabel jLabelPepsi;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JTextField jTextFieldFantaTotal;
    private javax.swing.JTextField jTextFieldLucozadeTotal;
    private javax.swing.JTextField jTextFieldMonsterTotal;
    private javax.swing.JTextField jTextFieldPepsiTotal;
    private javax.swing.JToggleButton jToggleButtonExit;
    // End of variables declaration//GEN-END:variables
}
